install:
- nvm install && nvm use
- npm install -g "npm@$(jq -r '.engines.npm' package.json)"
- npm ci
matrix:
  include:
  - os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
        - build-tools-23.0.1
        - android-23
    before_install:
      - yes | sdkmanager "platforms;android-23"
      - yes | sdkmanager "build-tools;23.0.1"
    script:
      - "./android/gradlew assembleRelease -p android/"