os: linux
language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-28.0.3
    - android-28
env:
    - JOB_NAME=ANDROID
script:
  - "./android/gradlew assembleRelease -p android/"