install:
- nvm install v8.12.0 && nvm use 8.12.0
- npm install -g "npm@$(jq -r '.engines.npm' package.json)"
- npm ci
matrix:
  include:
  - os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
        - build-tools-28.0.3
        - android-28
    before_install:
      - yes | sdkmanager "platforms;android-23"
      - yes | sdkmanager "build-tools;23.0.1"
      - openssl aes-256-cbc -K $enc_keystore_key -iv $enc_keystore_pass -in ./android/app/my-release-key.keystore.enc -out ./android/app/my-release-key.keystore -d
    script:
      - "./android/gradlew assembleRelease -p android/"
before_deploy:
      - export APP_VERSION=$(./gradlew :app:printVersionName)
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: ./android/app/build/outputs/apk/release/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    name: "$APP_VERSION"
    tag_name: "$APP_VERSION"
    on:
        tags: true
    