os: linux
language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-28.0.3
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
install:
  - npm ci
script:
  - "./android/gradlew assembleRelease -p android/"