include:
  - language: node_js
    node_js:
    - "8"
    script: .travis/ci_node.sh
os: linux
language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-28.0.3
    - android-28
script:
  - "./android/gradlew assembleRelease -p android/"